[project]
name = "python-stripe-example"
version = "0.0.0"
description = "Example project showing how to integrate Stripe payments into Python applications"
readme = "README.md"
dependencies = [
]
requires-python = "==3.14.2"
